export { salon } from './salon'
export { leistungen } from './leistungen'
export { oeffnungszeiten } from './oeffnungszeiten'
export { texte } from './texte'
export { arbeiten, galerie, heroFoto } from './fotos'
export type { Foto } from './fotos'
export { datenschutz, impressum } from './rechtliches'
export type { Rechtsabschnitt } from './rechtliches'
export { istOffen, offeneHinweise, todo } from './todo'
export type { Offen, Todo } from './todo'
export type * from './types'
