export { salon } from './salon'
export { leistungen } from './leistungen'
export { team } from './team'
export { oeffnungszeiten } from './oeffnungszeiten'
export { texte } from './texte'
export { datenschutz, impressum } from './rechtliches'
export type { Rechtsabschnitt } from './rechtliches'
export { istOffen, offeneHinweise, todo } from './todo'
export type { Offen, Todo } from './todo'
export type * from './types'
